#define MOUSEKEY_DELAY 0 
#define MOUSEKEY_INTERVAL 9
#define MOUSEKEY_MAX_SPEED 2.8
#define MOUSEKEY_TIME_TO_MAX 48
#define MOUSEKEY_WHEEL_TIME_TO_MAX 0
#define MOUSEKEY_WHEEL_MAX_SPEED 0.3
#define TAPPING_TERM 220
